language: php
php:
- 7.2
before_script:
  - composer install
script: phpunit tests

deploy:
  provider: heroku
  app: proyec1-travis
  on: master
  skip_cleanup: true
  api_key:
  secure: rRBQ7LpPMxnSrOnzdr259qY1hQMOUmHrt2N+WCxHVF5FJ3HFY1NXrieDEESHEQBBgh8vAu7ynMn4zgjtimtv3xdu/xGJCuvlU7XFFF9AGnSS+VFb35lu4dCiWKWW8QH+d89RuQs3d807yx2sLpplC7NagAxG1vNLABosL5kvDepc9BKTwZ8AvRdwzVcDnZOaOX6QiosVZzDTQ73JDiuxu3+xBkcX4sXRl/E6oOhWZUfi8FPDEgb1FJ78M39+0N1p3CpAw/z8XbE121IzqkBY+b5YHE4z8URGVg/5wVBcW6SI45mkG5i21sB8KAEVNNPzp1HbLFGiWbmqRvQr9W5OWv/AfLqm+sPOePXqx/3OC4tk4Fosrr4aegsHrwEJFX5HWUKSQG1DJ5m07MTqtlbUbl2tLLsqQdwfQGl2weSd0on278XQgPXreggVfrfwJC0Des7Psr3VNCqxfWExRpshuRztGPTDPjzak3/zyTmYONPbVdekNc+ECnLDJaaa6H939VzH1dRRXB89f/dgyKJUrprvaszxRJcz5R3nPeqj2VnfvgQEhiy8pqhW0tGmxCA+1RCAzvcl4HTcxWkl1+zLbnhzw7FpXOsmOSqSKt3QJuZGL3jxM8zz/xf+PNbEkIhYa+hYwNhIElOXiX/nec9/N3vHRm9tsvrJ/xyaM4NyHMU=
