language: php
php:
- 7.2
before_script:
  - composer install
script: phpunit tests

deploy:
  provider: heroku
  app: travis123
  on: master
  skip cleanup: true
  api_key:
secure: tWW0/URnd6IkBY64SgXbbKIavUBXVJq1BI6btcrV0QKa5D4VODNqhVKzpPxuu7RUw5ENhWEBiUu9+oYOUCtvvfafoDKaYO31bgUUXjjEhy8NZZkrKk/8pk6b+i/zP6tNbNyw3eRwGG5bQXrpdXXjBgsrUZyyX2fj4wb8B3QZAYllR8Ych5HQ16h1h5LR7IfjvFquDi8UudocLjSw+zCORQUs5EHfEoF1MCHmcwNZ12hRQQolofYtLLCAzocQU9aR5g9vV5LX8JYomgmxfP0vvmWHaU0GZE0CwS/M++5FAkB63ApobZMdg2Rf8JtKEKYUDG1Wtk59/mwd7myCMfN9paAda7sss5w9vVkm2OdsU/fe8W9/+w1P/+xspttKYnLznWI7RblbuWMVGDSNfA+VQ+D2Hz5g5xQFQtAzYEy3BE/b9nq9Wq5oqiKiu5DKK2M1SmuG9qalS5LjZzvqolZTBk9lxCipcVlPdAKfKSJKhLrXRi2y1wi+Q8oTBanBZsnyQa9gh4z4uavDvt0LIZN3dlLlpb6B010kbWyKfe8HEWL2Mdpe9fNJzvNg3mbDWp/bFY4Cs+/7E0zimD7p3z8vUD6ksI/0e8vr17LYI68tgl2lEx7eZxpSbdcMW0s5DpfBIH4yMvPFrx+PnL4kr0JtySzJyecAqRN3SLeRMprIj1w=
